#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "paper" / "figures_manifest.json"
OUTPUT = ROOT / "paper" / "sections" / "A2_figure_table_autogen.tex"


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "_": r"\_",
        "#": r"\#",
        "%": r"\%",
        "&": r"\&",
        "$": r"\$",
    }
    out = text
    for old, new in replacements.items():
        out = out.replace(old, new)
    return out


def main() -> int:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by python/scripts/ns_paper_appendix_figure_table.py")
    lines.append("% Source: paper/figures_manifest.json")
    lines.append("{\\small\\raggedright")
    lines.append("\\begin{description}")
    for e in entries:
        fig_id = str(e["id"])
        fig_class = str(e["class"])
        script = str(e["script"])
        png = str(e["artifact_png"])
        npz = str(e["artifact_npz"])

        lines.append(f"% id: {fig_id}")
        lines.append(
            "\\item[\\texttt{"
            + tex_escape(fig_id)
            + "}] \\textbf{class:} "
            + tex_escape(fig_class)
            + ";\n"
            + "  \\textbf{script:} \\nolinkurl{"
            + script
            + "}\\\\\n"
            + "  \\textbf{png:} \\nolinkurl{python/artifacts/"
            + png
            + "};\n"
            + "  \\textbf{npz:} \\nolinkurl{python/artifacts/"
            + npz
            + "}."
        )
    lines.append("\\end{description}")
    lines.append("}")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
